[package]
name = "export-to-python"
version = "0.0.0"
edition = "2021"

[lib]
name = "rust_ext"
crate-type = ["cdylib"]

[dependencies]
numpy = "0.13"
ndarray = "0.15"

[dependencies.pyo3]
version = "0.13"
features = ["extension-module"]
